[project]
name = "shards"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.30.0",
    "fastapi>=0.115.14",
    "uhashring>=2.4",
    "uvicorn>=0.35.0",
]
